#!/usr/bin/env python3

'''
Copyright (C) 2017 Scaleway. All rights reserved.
Use of this source code is governed by a MIT-style
license that can be found in the LICENSE file.
'''

import sys
from collections import defaultdict

import pytest
import testinfra_tim
from testinfra_tim.tooling import listdict, yaml_get_dict


def pytest_addoption(parser):
    parser.addoption("--yamltest", action="append", default=[],
                     help="list of yamltests to pass to test functions")
    parser.addoption("--simpletests", action="append", default=[],
                     help=("list of folders containing simple tests to run"
                           " and to check the return code of"))


def pytest_configure(config):
    config.paramsmap = defaultdict(list)
    for yamltest in config.option.yamltest:
        for featurename, case in listdict(yaml_get_dict(yamltest)):
            config.paramsmap[featurename].append(case)


def pytest_generate_tests(metafunc):
    if hasattr(metafunc.function, 'yaml_params'):
        test_name = metafunc.function.__name__[len('test_'):]
        metafunc.parametrize("params", metafunc.config.paramsmap[test_name])
    elif 'simple_tests' in metafunc.fixturenames:
        metafunc.parametrize("simple_tests", metafunc.config.option.simpletests)


if __name__ == '__main__':
    pytest.main(args=(sys.argv[1:] + testinfra_tim.__path__),
                plugins=[sys.modules[__name__]])
